development:
  app_host: APP_HOST_HERE # e.g. osb.mydomain.com
  app_protocol: http
  activemerchant_billing_mode: test
  demo_mode: false
  wkhtmltopdf_path: /Users/macbookair/.rbenv/shims/wkhtmltopdf  #run "which wkhtmltopdf" you will get path
  encryption_key: b7d3b97152beba5d1fe55c254d53d9b7c91f211c3dc9841e37bcdfd75cb39f8bbbd8ec39e439f191aedf1bf503692f6cb1572dc27cd66811692b826d30c5c010

  paypal:
    enabled: false
    url: https://www.sandbox.paypal.com/cgi-bin/webscr?
    business: YOUR_PAYPAL_BUSINESS

  smtp_setting:
    address: smtp.gmail.com
    port: 587
    authentication: :plain
    enable_starttls_auto: true
    user_name: YOUR_EMAIL_HERE
    password: YOUR_PASSWORD_HERE

  quickbooks:
    # QuickBooksApp account key and secret
    consumer_key: YOUR_QUICKBOOKS_APP_CLIENT_ID
    consumer_secret: YOUR_QUICKBOOKS_APP_CLIENT_SECRET

production:
  app_host: APP_HOST_HERE # e.g. osb.mydomain.com
  app_protocol: http
  activemerchant_billing_mode: test
  wkhtmltopdf_path: YOUR_WKHTMLTOPDF_PATH  #run "which wkhtmltopdf" you will get path
  encryption_key: ENTER-YOUR-ENCRYPTED-KEY-HERE

  paypal:
    enabled: false
    url: https://www.paypal.com/cgi-bin/webscr?
    business: YOUR_PAYPAL_BUSINESS

  smtp_setting:
    address: smtp.gmail.com
    port: 587
    authentication: :plain
    enable_starttls_auto: true
    user_name: YOUR_EMAIL_HERE
    password: YOUR_PASSWORD_HERE

  quickbooks:
    # QuickBooksApp account key and secret
    consume_key: YOUR_QUICKBOOKS_APP_CLIENT_ID
    consumer_secret: YOUR_QUICKBOOKS_APP_CLIENT_SECRET